apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepstream-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepstream-app
  template:
    metadata:
      labels:
        app: deepstream-app
    spec:
      containers:
      - name: deepstream-container
        image: "hermanleong/deepstream-demo:v1.1"
        ports:
        - containerPort: 8554
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: deepstream-service
spec:
  type: LoadBalancer
  ports:
  - port: 8554
    targetPort: 8554
    protocol: TCP
    name: deepstream-port
  selector:
    app: deepstream-app
