apiVersion: v1
kind: Service
metadata:
  name: deepstream-demo-service
  namespace: deepstream
spec:
  ports:
    - name: rtsp
      port: 80
      protocol: TCP
      targetPort: 8554
  selector:
    k8s-app: deepstream-demo
  type: LoadBalancer
